language: python

matrix:
  include:
    - os: linux
      python: "3.5"

    - os: linux
      python: "3.4"

    - os: linux
      python: "3.3"

    - os: linux
      python: "2.7"

    - os: linux
      python: "pypy"
      sudo: required

    - os: osx
      language: generic
      python: "3.5"
      env:
        - PYTHONVERSION=3.5.2

    - os: osx
      language: generic
      python: "3.4"
      env:
        - PYTHONVERSION=3.4.5

    - os: osx
      language: generic
      python: "3.3"
      env:
        - PYTHONVERSION=3.3.6

    - os: osx
      language: generic
      python: "2.7"
      env:
        - PYTHONVERSION=2.7.12

install:
    - ./ci/travis-install.sh
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
    - pip install tox-travis cffi codecov
    - pip install cffi
    - pip install codecov

before_script:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ulimit -c unlimited -S; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
    - python setup.py install
    - tox

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then eval "$(pyenv init -)"; fi
    - codecov -X gcov --required --file coverage.xml
